spring: 
    profiles: 
        active: 
        - dev
---
server: 
    port: 8001
    
spring: 
    profiles: dev
    application: 
        name: springcloud-config-system-client
    datasource: 
        type: com.alibaba.druid.pool.DruidDataSource
        # driver-clas-name: org.gjt.mm.mysql.Driver
        driver-class-name: com.mysql.jdbc.Driver        # mysql 驱动包
        url: jdbc:mysql://localhost:3306/springcloud01?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC    # 数据库名称
        username: root
        password: 123456
        dbcp2:
            min-idle: 5           # 数据库连接池最小维持链接数
            initial-size: 5       # 初始化连接数
            max-total: 5          # 最大连接数 
            max-wait-millis: 200  # 等待连获取的最大时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis 配置文件所在的路径
  type-aliases-package: indi.jsees.springcloud.domain # 所有 Entity 别名所在的包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                 # mapper映射文件

eureka: 
  client: 
    service-url: 
      # (单个eureka 服务)defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-system8001 # 自定义服务名称信息
    prefer-ip-address: true                   # 访问路径可以显示 ip 地址
      
      
info: 
  app.name: springcloud-jsees
  company.name: www.baidu.com
  build.artifactId: $priject.artifactId$
  build.version: $project.version$
  
---
server: 
    port: 8001
    
spring: 
    profiles: test
    application: 
        name: springcloud-config-system-client
    datasource: 
        type: com.alibaba.druid.pool.DruidDataSource
        # driver-clas-name: org.gjt.mm.mysql.Driver
        driver-class-name: com.mysql.jdbc.Driver        # mysql 驱动包
        url: jdbc:mysql://localhost:3306/springcloud03?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC    # 数据库名称
        username: root
        password: 123456
        dbcp2:
            min-idle: 5           # 数据库连接池最小维持链接数
            initial-size: 5       # 初始化连接数
            max-total: 5          # 最大连接数 
            max-wait-millis: 200  # 等待连获取的最大时间
            
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis 配置文件所在的路径
  type-aliases-package: indi.jsees.springcloud.domain # 所有 Entity 别名所在的包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                 # mapper映射文件

eureka: 
  client: 
    service-url: 
      # (单个eureka 服务)defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-system8001 # 自定义服务名称信息
    prefer-ip-address: true                   # 访问路径可以显示 ip 地址
      
      
info: 
  app.name: springcloud-jseesd
  company.name: www.baidu.com
  build.artifactId: $priject.artifactId$
  build.version: $project.version$